// GENERATED by scripts/generate-base-rates.mjs — do not edit by hand.
// Source: artifacts/reports/ace_competing_risks_v1_scorecard.json
//
// Empirical base rates for "after a shock, what happens next", from an
// Aalen-Johansen competing-risks fit.
//
//   subjects (train)     3837
//   total mainshocks     4633
//   sealed holdout       796
//   censored             1586
//   worst holdout error  0.0352
//   naive KM baseline    0.2877
//
// Competing risks, not independent survival: escalation and continuation
// FORECLOSE each other, and the naive Kaplan-Meier treatment that censors the
// competing cause is wrong by 28.8 points at worst against 3.5 for this fit.
//
// REFERENCE CLASS, stated plainly: these rates were measured on MARKET shocks
// (|return| >= 2 sigma), not on news events. Using them as a prior for a news
// book is a reference-class transfer. It is a far better starting point than an
// authored constant, and it is not the same population — any consumer must
// surface that, which is why `BASE_RATE_REFERENCE_CLASS` exists and is shown.

export interface BaseRateRow {
  /** Horizon in days since the shock. */
  days: number;
  /** Cumulative incidence of escalation by this horizon. */
  escalation: number;
  /** Cumulative incidence of continuation-without-escalation. */
  continuation: number;
  /** Residual: neither has occurred by this horizon. */
  neither: number;
}

export const SHOCK_BASE_RATES: BaseRateRow[] = [
  { days: 0.0011, escalation: 0.003909, continuation: 0.006349, neither: 0.9897419999999999 },
  { days: 0.0024, escalation: 0.006796, continuation: 0.020068, neither: 0.973136 },
  { days: 0.0043, escalation: 0.00834, continuation: 0.03513, neither: 0.95653 },
  { days: 0.0067, escalation: 0.009122, continuation: 0.050954, neither: 0.939924 },
  { days: 0.0105, escalation: 0.010164, continuation: 0.066517, neither: 0.923319 },
  { days: 0.0166, escalation: 0.011207, continuation: 0.082081, neither: 0.9067120000000001 },
  { days: 0.0269, escalation: 0.014073, continuation: 0.09582, neither: 0.890107 },
  { days: 0.0446, escalation: 0.015214, continuation: 0.111285, neither: 0.8735010000000001 },
  { days: 0.0722, escalation: 0.018243, continuation: 0.124861, neither: 0.856896 },
  { days: 0.107, escalation: 0.020589, continuation: 0.139122, neither: 0.8402890000000001 },
  { days: 0.1689, escalation: 0.021892, continuation: 0.154424, neither: 0.823684 },
  { days: 0.2487, escalation: 0.023977, continuation: 0.168945, neither: 0.807078 },
  { days: 0.3453, escalation: 0.024759, continuation: 0.184769, neither: 0.7904720000000001 },
  { days: 0.4945, escalation: 0.026583, continuation: 0.199551, neither: 0.7738659999999999 },
  { days: 0.6777, escalation: 0.028147, continuation: 0.214593, neither: 0.7572599999999999 },
  { days: 0.8796, escalation: 0.029971, continuation: 0.229374, neither: 0.7406550000000001 },
  { days: 1.2226, escalation: 0.031274, continuation: 0.244677, neither: 0.7240489999999999 },
  { days: 1.6967, escalation: 0.033099, continuation: 0.259459, neither: 0.707442 },
  { days: 2.2837, escalation: 0.036747, continuation: 0.272416, neither: 0.690837 },
  { days: 3.0532, escalation: 0.038311, continuation: 0.287458, neither: 0.674231 },
  { days: 3.7879, escalation: 0.040917, continuation: 0.301457, neither: 0.657626 },
  { days: 4.7981, escalation: 0.044305, continuation: 0.314675, neither: 0.6410199999999999 },
  { days: 5.8769, escalation: 0.046912, continuation: 0.328675, neither: 0.6244130000000001 },
  { days: 7.2662, escalation: 0.049257, continuation: 0.342935, neither: 0.607808 },
  { days: 8.506, escalation: 0.051082, continuation: 0.357717, neither: 0.5912010000000001 },
  { days: 9.7923, escalation: 0.052645, continuation: 0.372759, neither: 0.5745959999999999 },
  { days: 11.1238, escalation: 0.05447, continuation: 0.38754, neither: 0.55799 },
  { days: 12.4235, escalation: 0.056555, continuation: 0.402061, neither: 0.541384 },
  { days: 13.9969, escalation: 0.059682, continuation: 0.41554, neither: 0.524778 },
  { days: 16.1164, escalation: 0.062846, continuation: 0.428981, neither: 0.508173 },
  { days: 18.2447, escalation: 0.065155, continuation: 0.443278, neither: 0.49156700000000003 },
  { days: 20.001, escalation: 0.067911, continuation: 0.457128, neither: 0.47496099999999997 },
  { days: 22.2228, escalation: 0.070628, continuation: 0.471017, neither: 0.45835499999999996 },
  { days: 24.4708, escalation: 0.071931, continuation: 0.48632, neither: 0.44174900000000006 },
  { days: 27.6897, escalation: 0.073495, continuation: 0.501362, neither: 0.42514300000000005 },
  { days: 30, escalation: 0.075319, continuation: 0.511337, neither: 0.41334399999999993 },
];

/** Out-of-sample calibration of the curves above, on the sealed holdout. */
export const BASE_RATE_CALIBRATION = [
  { days: 1, cause: "escalation", predicted: 0.03, realized: 0.0226, error: 0.0074, n: 796 },
  { days: 1, cause: "continuation", predicted: 0.2294, realized: 0.2236, error: 0.0058, n: 796 },
  { days: 3, cause: "escalation", predicted: 0.0367, realized: 0.0251, error: 0.0116, n: 796 },
  { days: 3, cause: "continuation", predicted: 0.2724, realized: 0.2663, error: 0.0061, n: 796 },
  { days: 7, cause: "escalation", predicted: 0.0469, realized: 0.0364, error: 0.0105, n: 796 },
  { days: 7, cause: "continuation", predicted: 0.3287, realized: 0.3191, error: 0.0096, n: 796 },
  { days: 14, cause: "escalation", predicted: 0.0597, realized: 0.044, error: 0.0157, n: 796 },
  { days: 14, cause: "continuation", predicted: 0.4155, realized: 0.3844, error: 0.0311, n: 796 },
  { days: 30, cause: "escalation", predicted: 0.0753, realized: 0.0641, error: 0.0112, n: 796 },
  { days: 30, cause: "continuation", predicted: 0.5113, realized: 0.4761, error: 0.0352, n: 796 },
] as const;

export const BASE_RATE_PROVENANCE = {
  model: "aalen_johansen_competing_risks",
  modelId: "ace_competing_risks",
  version: "v1",
  nSubjects: 3837,
  nHoldout: 796,
  worstHoldoutError: 0.0352,
  naiveBaselineWorstError: 0.2877369820172009,
  causes: ["escalation","continuation"],
} as const;

export const BASE_RATE_REFERENCE_CLASS =
  "Measured on market shocks (|return| >= 2 sigma), not on news events. " +
  "Applying it to a news book is a reference-class transfer.";

/**
 * Cumulative incidence at an arbitrary horizon, linearly interpolated.
 *
 * A step function evaluated between its knots would jump; the curve is
 * monotone and smooth enough between grid points that interpolating is the
 * honest read. Outside the grid it clamps to the nearest end rather than
 * extrapolating a survival curve it never measured.
 */
export function baseRateAt(days: number): BaseRateRow {
  const g = SHOCK_BASE_RATES;
  if (!g.length) throw new Error("base rates are empty");
  if (days <= g[0]!.days) return g[0]!;
  const last = g[g.length - 1]!;
  if (days >= last.days) return last;
  for (let i = 1; i < g.length; i++) {
    const a = g[i - 1]!;
    const b = g[i]!;
    if (days <= b.days) {
      const t = (days - a.days) / (b.days - a.days || 1);
      const mix = (x: number, y: number) => x + (y - x) * t;
      return {
        days,
        escalation: mix(a.escalation, b.escalation),
        continuation: mix(a.continuation, b.continuation),
        neither: mix(a.neither, b.neither),
      };
    }
  }
  return last;
}
