// GENERATED by scripts/generate-cascade-rates.mjs — do not edit by hand.
// Source: artifacts/reports/ace_gdelt_cascade_v1_scorecard.json
//
// Measured self-excitation in material conflict events (GDELT, CAMEO quad
// class 4), by the country the action occurred in.
//
// Only countries that cleared the gate appear. A country that failed, or was
// never fitted, is ABSENT — the app must render that absence rather than fall
// back to a default.
//
// WHAT IS ESTABLISHED: escalation clusters. The likelihood-ratio test against a
// homogeneous Poisson process clears p = 0.0084468 on every country here, and
// every one gains out of sample under parameters fitted before the holdout.
//
// WHAT IS NOT: the intensity's exact shape. Pooled Ogata residuals reject a
// CONTINUOUS Exp(1) null — but these events sit on a daily grid where 47% of
// gaps are exactly one day, and a continuous null rejects gridded data for that
// reason alone. Correcting for the floor does not restore the fit either, so
// discretization and kernel shape are confounded and neither is established.
//
// Consequence for display: the branching ratio is an ORDER-OF-MAGNITUDE
// statement about how much one escalation breeds. It is not a three-digit
// estimate and must not be rendered as one.

export interface CascadeRate {
  /** FIPS 10-4 country code, as GDELT emits it. */
  code: string;
  name: string;
  /** Spike days the fit was built from. */
  spikeDays: number;
  /**
   * Expected direct offspring per event. Below 1 the process is stationary —
   * escalations amplify and die out rather than running away.
   */
  branchingRatio: number;
  /** How fast the excitation decays. Near one day across the board. */
  excitationHalfLifeDays: number | null;
  /** Total events per independent event, across all generations. */
  cascadeMultiplier: number | null;
  directOffspringWithinHorizon: number | null;
  /** Likelihood-ratio p against a homogeneous Poisson process. */
  lrPValue: number;
  /** Out-of-sample log-likelihood gain over Poisson. */
  oosGainOverPoisson: number;
  firstEvent: string;
  lastEvent: string;
  meanEventsPerDay: number;
}

export const CASCADE_RATES: Record<string, CascadeRate> = {
  "IR": {
    code: "IR",
    name: "Iran",
    spikeDays: 68,
    branchingRatio: 0.575602,
    excitationHalfLifeDays: 1.1925,
    cascadeMultiplier: 2.3563,
    directOffspringWithinHorizon: 0.5754,
    lrPValue: 0,
    oosGainOverPoisson: 15.471,
    firstEvent: "2022-03-13",
    lastEvent: "2026-01-15",
    meanEventsPerDay: 56.04,
  },
  "LE": {
    code: "LE",
    name: "Lebanon",
    spikeDays: 46,
    branchingRatio: 0.538542,
    excitationHalfLifeDays: 1.1807,
    cascadeMultiplier: 2.167,
    directOffspringWithinHorizon: 0.5384,
    lrPValue: 0,
    oosGainOverPoisson: 14.916,
    firstEvent: "2022-04-01",
    lastEvent: "2025-11-24",
    meanEventsPerDay: 24.01,
  },
  "SY": {
    code: "SY",
    name: "Syria",
    spikeDays: 50,
    branchingRatio: 0.52587,
    excitationHalfLifeDays: 1.1481,
    cascadeMultiplier: 2.1091,
    directOffspringWithinHorizon: 0.5258,
    lrPValue: 0,
    oosGainOverPoisson: 11.648,
    firstEvent: "2022-04-13",
    lastEvent: "2025-12-20",
    meanEventsPerDay: 30.13,
  },
  "CU": {
    code: "CU",
    name: "Cuba",
    spikeDays: 43,
    branchingRatio: 0.412877,
    excitationHalfLifeDays: 0.934,
    cascadeMultiplier: 1.7032,
    directOffspringWithinHorizon: 0.4129,
    lrPValue: 5.4e-7,
    oosGainOverPoisson: 8.67,
    firstEvent: "2022-05-06",
    lastEvent: "2026-01-08",
    meanEventsPerDay: 5.47,
  },
  "PK": {
    code: "PK",
    name: "Pakistan",
    spikeDays: 53,
    branchingRatio: 0.220638,
    excitationHalfLifeDays: 0.942,
    cascadeMultiplier: 1.2831,
    directOffspringWithinHorizon: 0.2206,
    lrPValue: 0.0084468,
    oosGainOverPoisson: 8.268,
    firstEvent: "2022-04-26",
    lastEvent: "2026-02-01",
    meanEventsPerDay: 92.59,
  },
  "ES": {
    code: "ES",
    name: "El Salvador",
    spikeDays: 47,
    branchingRatio: 0.358513,
    excitationHalfLifeDays: 1.2164,
    cascadeMultiplier: 1.5589,
    directOffspringWithinHorizon: 0.3584,
    lrPValue: 0.00003704,
    oosGainOverPoisson: 6.936,
    firstEvent: "2022-03-12",
    lastEvent: "2025-12-22",
    meanEventsPerDay: 5.13,
  },
  "WE": {
    code: "WE",
    name: "West Bank",
    spikeDays: 43,
    branchingRatio: 0.412362,
    excitationHalfLifeDays: 1.4813,
    cascadeMultiplier: 1.7017,
    directOffspringWithinHorizon: 0.4118,
    lrPValue: 0.00001267,
    oosGainOverPoisson: 2.523,
    firstEvent: "2022-03-15",
    lastEvent: "2025-11-13",
    meanEventsPerDay: 14.1,
  },
  "BG": {
    code: "BG",
    name: "Bangladesh",
    spikeDays: 46,
    branchingRatio: 0.440748,
    excitationHalfLifeDays: 0.9549,
    cascadeMultiplier: 1.7881,
    directOffspringWithinHorizon: 0.4407,
    lrPValue: 1e-8,
    oosGainOverPoisson: 0.172,
    firstEvent: "2022-04-13",
    lastEvent: "2025-12-19",
    meanEventsPerDay: 27.12,
  },
};

export const CASCADE_RUN = {
  nMaterialEvents: 5792921,
  sigma: 2,
  windowDays: 60,
  testFraction: 0.3,
  nFitted: 10,
  nPassing: 8,
  selection: {"fitted":10,"excluded_holdout_size":16,"excluded_too_few_spikes":36,"basis":"sample size, not result"},
  specification: {
    trainKsP: 0.000097,
    holdoutKsP: 0.028419,
    residualFloor: 0.1457,
    massUnreachableOnDailyGrid: 0.1356,
    conditionalKsP: 0.000012,
    note:
      "Pooled Ogata residuals reject a continuous Exp(1) null, but these events " +
      "sit on a daily grid where no two can be closer than one day. Discretization " +
      "and kernel shape are confounded; neither is established. Treat the " +
      "branching ratio as approximate.",
  },
} as const;

export function cascadeFor(code: string): CascadeRate | undefined {
  return CASCADE_RATES[code.toUpperCase()];
}

/** Every measured cascade, strongest out-of-sample evidence first. */
export function allCascades(): CascadeRate[] {
  return Object.values(CASCADE_RATES).sort((a, b) => b.oosGainOverPoisson - a.oosGainOverPoisson);
}

/**
 * Aliases an event's extracted entities plausibly use for a measured country.
 *
 * Deliberately conservative and explicit rather than fuzzy: a wrong match
 * attaches one country's measured cascade to another country's event, which is
 * worse than showing nothing. Anything not listed simply does not match.
 */
const ALIASES: Record<string, string[]> = {
  SY: ["syria", "syrian", "damascus"],
  LE: ["lebanon", "lebanese", "beirut", "hezbollah"],
  GZ: ["gaza", "gazan", "hamas"],
  IR: ["iran", "iranian", "tehran", "irgc"],
  IS: ["israel", "israeli", "idf", "jerusalem", "tel aviv"],
  WE: ["west bank", "ramallah"],
  PK: ["pakistan", "pakistani", "islamabad"],
  ES: ["el salvador", "salvadoran"],
  TU: ["turkey", "turkish", "ankara"],
  AF: ["afghanistan", "afghan", "kabul", "taliban"],
  SO: ["somalia", "somali", "mogadishu", "al-shabaab"],
  UP: ["ukraine", "ukrainian", "kyiv", "kiev"],
  RS: ["russia", "russian", "moscow", "kremlin"],
  TW: ["taiwan", "taiwanese", "taipei"],
  KN: ["north korea", "dprk", "pyongyang"],
  BG: ["bangladesh", "dhaka"],
};

/**
 * Measured cascades relevant to an event, by its extracted entities.
 *
 * Returns only countries that cleared the gate. An event about somewhere
 * unmeasured returns nothing, and the caller must render that rather than
 * substitute a global average.
 */
export function cascadesForEntities(entities: string[]): CascadeRate[] {
  const hay = entities.map((e) => e.toLowerCase());
  const hit = new Set<string>();
  for (const [code, names] of Object.entries(ALIASES)) {
    if (!CASCADE_RATES[code]) continue;
    if (names.some((n) => hay.some((h) => h === n || h.includes(n)))) hit.add(code);
  }
  return [...hit]
    .map((c) => CASCADE_RATES[c]!)
    .sort((a, b) => b.oosGainOverPoisson - a.oosGainOverPoisson);
}
