// GENERATED by scripts/generate-cascade-rates.mjs — do not edit by hand.
// Source: artifacts/reports/ace_gdelt_cascade_v1_scorecard.json
//
// Measured self-excitation in material conflict events (GDELT, CAMEO quad
// class 4), by the country the action occurred in.
//
// Only countries that cleared the gate appear. A country that failed, or was
// never fitted, is ABSENT — the app must render that absence rather than fall
// back to a default.
//
// WHAT IS ESTABLISHED: escalation clusters. The likelihood-ratio test against a
// homogeneous Poisson process clears p = 0.00185696 on every country here, and
// every one gains out of sample under parameters fitted before the holdout.
//
// WHAT IS NOT: the intensity's exact shape. Pooled Ogata residuals reject a
// CONTINUOUS Exp(1) null — but these events sit on a daily grid where 47% of
// gaps are exactly one day, and a continuous null rejects gridded data for that
// reason alone. Correcting for the floor does not restore the fit either, so
// discretization and kernel shape are confounded and neither is established.
//
// Consequence for display: the branching ratio is an ORDER-OF-MAGNITUDE
// statement about how much one escalation breeds. It is not a three-digit
// estimate and must not be rendered as one.

export interface CascadeRate {
  /** FIPS 10-4 country code, as GDELT emits it. */
  code: string;
  name: string;
  /** Spike days the fit was built from. */
  spikeDays: number;
  /**
   * Expected direct offspring per event. Below 1 the process is stationary —
   * escalations amplify and die out rather than running away.
   */
  branchingRatio: number;
  /** How fast the excitation decays. Near one day across the board. */
  excitationHalfLifeDays: number | null;
  /** Total events per independent event, across all generations. */
  cascadeMultiplier: number | null;
  directOffspringWithinHorizon: number | null;
  /** Likelihood-ratio p against a homogeneous Poisson process. */
  lrPValue: number;
  /** Out-of-sample log-likelihood gain over Poisson. */
  oosGainOverPoisson: number;
  firstEvent: string;
  lastEvent: string;
  meanEventsPerDay: number;
}

export const CASCADE_RATES: Record<string, CascadeRate> = {
  "LE": {
    code: "LE",
    name: "Lebanon",
    spikeDays: 52,
    branchingRatio: 0.566322,
    excitationHalfLifeDays: 1.1721,
    cascadeMultiplier: 2.3059,
    directOffspringWithinHorizon: 0.5662,
    lrPValue: 0,
    oosGainOverPoisson: 17.064,
    firstEvent: "2022-04-01",
    lastEvent: "2026-03-07",
    meanEventsPerDay: 26.13,
  },
  "IR": {
    code: "IR",
    name: "Iran",
    spikeDays: 78,
    branchingRatio: 0.514831,
    excitationHalfLifeDays: 1.2404,
    cascadeMultiplier: 2.0611,
    directOffspringWithinHorizon: 0.5146,
    lrPValue: 0,
    oosGainOverPoisson: 16.261,
    firstEvent: "2022-03-13",
    lastEvent: "2026-07-09",
    meanEventsPerDay: 77.05,
  },
  "SY": {
    code: "SY",
    name: "Syria",
    spikeDays: 52,
    branchingRatio: 0.54041,
    excitationHalfLifeDays: 1.1602,
    cascadeMultiplier: 2.1759,
    directOffspringWithinHorizon: 0.5403,
    lrPValue: 0,
    oosGainOverPoisson: 12.721,
    firstEvent: "2022-04-13",
    lastEvent: "2026-08-11",
    meanEventsPerDay: 28.22,
  },
  "PK": {
    code: "PK",
    name: "Pakistan",
    spikeDays: 62,
    branchingRatio: 0.2606,
    excitationHalfLifeDays: 0.9703,
    cascadeMultiplier: 1.3524,
    directOffspringWithinHorizon: 0.2606,
    lrPValue: 0.00065921,
    oosGainOverPoisson: 10.625,
    firstEvent: "2022-04-26",
    lastEvent: "2026-06-29",
    meanEventsPerDay: 89.05,
  },
  "CU": {
    code: "CU",
    name: "Cuba",
    spikeDays: 52,
    branchingRatio: 0.385465,
    excitationHalfLifeDays: 0.8768,
    cascadeMultiplier: 1.6272,
    directOffspringWithinHorizon: 0.3855,
    lrPValue: 9e-8,
    oosGainOverPoisson: 10.255,
    firstEvent: "2022-05-06",
    lastEvent: "2026-08-21",
    meanEventsPerDay: 6.47,
  },
  "WE": {
    code: "WE",
    name: "West Bank",
    spikeDays: 54,
    branchingRatio: 0.401355,
    excitationHalfLifeDays: 1.2569,
    cascadeMultiplier: 1.6704,
    directOffspringWithinHorizon: 0.4012,
    lrPValue: 3.3e-7,
    oosGainOverPoisson: 7.644,
    firstEvent: "2022-03-15",
    lastEvent: "2026-07-27",
    meanEventsPerDay: 13.43,
  },
  "NP": {
    code: "NP",
    name: "Nepal",
    spikeDays: 48,
    branchingRatio: 0.461166,
    excitationHalfLifeDays: 0.9925,
    cascadeMultiplier: 1.8559,
    directOffspringWithinHorizon: 0.4611,
    lrPValue: 0,
    oosGainOverPoisson: 6.258,
    firstEvent: "2022-04-29",
    lastEvent: "2026-08-29",
    meanEventsPerDay: 7.29,
  },
  "GR": {
    code: "GR",
    name: "Greece",
    spikeDays: 43,
    branchingRatio: 0.402831,
    excitationHalfLifeDays: 1.6465,
    cascadeMultiplier: 1.6746,
    directOffspringWithinHorizon: 0.4017,
    lrPValue: 0.00002307,
    oosGainOverPoisson: 4.626,
    firstEvent: "2022-07-20",
    lastEvent: "2026-08-03",
    meanEventsPerDay: 12.53,
  },
  "RW": {
    code: "RW",
    name: "Rwanda",
    spikeDays: 44,
    branchingRatio: 0.389727,
    excitationHalfLifeDays: 1.0915,
    cascadeMultiplier: 1.6386,
    directOffspringWithinHorizon: 0.3897,
    lrPValue: 8.1e-7,
    oosGainOverPoisson: 3.773,
    firstEvent: "2022-03-08",
    lastEvent: "2026-05-18",
    meanEventsPerDay: 5.7,
  },
  "AF": {
    code: "AF",
    name: "Afghanistan",
    spikeDays: 49,
    branchingRatio: 0.332302,
    excitationHalfLifeDays: 1.1488,
    cascadeMultiplier: 1.4977,
    directOffspringWithinHorizon: 0.3322,
    lrPValue: 0.00001233,
    oosGainOverPoisson: 3.765,
    firstEvent: "2022-04-19",
    lastEvent: "2026-08-14",
    meanEventsPerDay: 30.71,
  },
  "IN": {
    code: "IN",
    name: "India",
    spikeDays: 45,
    branchingRatio: 0.482671,
    excitationHalfLifeDays: 1.4983,
    cascadeMultiplier: 1.933,
    directOffspringWithinHorizon: 0.4819,
    lrPValue: 0,
    oosGainOverPoisson: 3.67,
    firstEvent: "2022-04-21",
    lastEvent: "2026-07-23",
    meanEventsPerDay: 171.78,
  },
  "IS": {
    code: "IS",
    name: "Israel",
    spikeDays: 56,
    branchingRatio: 0.636247,
    excitationHalfLifeDays: 1.3059,
    cascadeMultiplier: 2.7491,
    directOffspringWithinHorizon: 0.6359,
    lrPValue: 0,
    oosGainOverPoisson: 3.388,
    firstEvent: "2022-03-28",
    lastEvent: "2026-06-08",
    meanEventsPerDay: 260.62,
  },
  "TU": {
    code: "TU",
    name: "Turkey",
    spikeDays: 50,
    branchingRatio: 0.433622,
    excitationHalfLifeDays: 1.7453,
    cascadeMultiplier: 1.7656,
    directOffspringWithinHorizon: 0.432,
    lrPValue: 3.8e-7,
    oosGainOverPoisson: 2.92,
    firstEvent: "2022-04-25",
    lastEvent: "2026-07-31",
    meanEventsPerDay: 20.46,
  },
  "NG": {
    code: "NG",
    name: "Niger",
    spikeDays: 43,
    branchingRatio: 0.505016,
    excitationHalfLifeDays: 1.7009,
    cascadeMultiplier: 2.0203,
    directOffspringWithinHorizon: 0.5033,
    lrPValue: 0,
    oosGainOverPoisson: 2.399,
    firstEvent: "2022-10-18",
    lastEvent: "2026-08-30",
    meanEventsPerDay: 7.06,
  },
  "BR": {
    code: "BR",
    name: "Brazil",
    spikeDays: 43,
    branchingRatio: 0.269417,
    excitationHalfLifeDays: 1.1185,
    cascadeMultiplier: 1.3688,
    directOffspringWithinHorizon: 0.2694,
    lrPValue: 0.00185696,
    oosGainOverPoisson: 1.746,
    firstEvent: "2022-04-28",
    lastEvent: "2026-07-24",
    meanEventsPerDay: 11.23,
  },
};

export const CASCADE_RUN = {
  nMaterialEvents: 6472236,
  sigma: 2,
  windowDays: 60,
  testFraction: 0.3,
  nFitted: 20,
  nPassing: 15,
  selection: {"fitted":20,"excluded_holdout_size":13,"excluded_too_few_spikes":26,"basis":"sample size, not result"},
  specification: {
    trainKsP: 0,
    holdoutKsP: 0.000398,
    residualFloor: 0.148,
    massUnreachableOnDailyGrid: 0.1376,
    conditionalKsP: 0,
    note:
      "Pooled Ogata residuals reject a continuous Exp(1) null, but these events " +
      "sit on a daily grid where no two can be closer than one day. Discretization " +
      "and kernel shape are confounded; neither is established. Treat the " +
      "branching ratio as approximate.",
  },
} as const;

export function cascadeFor(code: string): CascadeRate | undefined {
  return CASCADE_RATES[code.toUpperCase()];
}

/** Every measured cascade, strongest out-of-sample evidence first. */
export function allCascades(): CascadeRate[] {
  return Object.values(CASCADE_RATES).sort((a, b) => b.oosGainOverPoisson - a.oosGainOverPoisson);
}
