/**
 * Server-side factor-engine state for the macro workstation.
 *
 * `macro-state.json` is generated by `scripts/generate-macro-state.mjs` from
 * the Python runs (Factor State API, DFM news decomposition, regime verdicts,
 * panel freshness). It never reaches the client bundle; the page fetches it on
 * request, the same split `macro-detail` uses.
 */
import state from "./macro-state.json";

export interface FactorDriver {
  seriesId: string;
  label: string;
  loading: number | null;
  z: number | null;
  contribution: number | null;
  through: string | null;
  daysBehind: number | null;
}

export interface FactorRow {
  id: string;
  domain: string;
  name: string;
  asOf: string;
  lastFit: string;
  modelVersion: string | null;
  level: number | null;
  percentile: number | null;
  direction: string | null;
  momentum: number | null;
  acceleration: number | null;
  change1m: number | null;
  change3m: number | null;
  changeSincePreviousRun: number | null;
  freshnessDays: number | null;
  coverage: number | null;
  activeSeries: number | null;
  missingSeries: number | null;
  varianceShare: number | null;
  path: { at: string; level: number }[];
  drivers: FactorDriver[];
}

export interface ReleaseRow {
  seriesId: string;
  label: string;
  block: string;
  observationDate: string;
  observed: number | null;
  expected: number | null;
  surprise: number | null;
  weight: number | null;
  impact: number | null;
}

export interface NewsBlock {
  block: string;
  proxySeries: string | null;
  proxyLabel: string | null;
  impactDate: string | null;
  estimatePrevious: number | null;
  estimateUpdated: number | null;
  news: number | null;
  revisions: number | null;
  total: number | null;
  releases: ReleaseRow[];
}

export interface RegimeRow {
  factor: string;
  levelRegime: boolean;
  verdict: string | null;
  meanSeparation: number | null;
  meanBuysBic: number | null;
  varianceRatio: number | null;
  durations: number[] | null;
}

export interface SeriesMeta {
  label: string;
  units: string | null;
  source: string | null;
  transformation: string | null;
  releaseLagDays: number | null;
  through: string | null;
  daysBehind: number | null;
  frequency: string | null;
}

export interface MacroState {
  available: true;
  generatedAt: string;
  provenance: Record<string, { file: string; sha256: string }>;
  panel: { asOf: string; used: number; size: number; groups: string[] };
  factorModel: { asOf: string; lastFit: string; method: string; version: string | null; validation: string };
  factors: FactorRow[];
  whatChanged: {
    previousAsOf: string;
    updatedAsOf: string;
    lookbackDays: number;
    method: string;
    units: string;
    validation: string;
    blocks: NewsBlock[];
    releases: ReleaseRow[];
  };
  regimes: {
    asOf: string;
    method: string;
    converged: boolean;
    status: string;
    validation: string;
    series: number;
    factors: RegimeRow[];
  } | null;
  series: Record<string, SeriesMeta>;
}

export interface MacroStateUnavailable {
  available: false;
  reason: string;
}

const artifact = state as unknown as Omit<MacroState, "available">;

export function macroState(): MacroState | MacroStateUnavailable {
  if (!artifact?.factors?.length) {
    return { available: false, reason: "the factor-engine artifact has no factors" };
  }
  if (!artifact.whatChanged?.updatedAsOf) {
    return { available: false, reason: "the factor-engine artifact has no news decomposition" };
  }
  return { available: true, ...artifact };
}
