import type { RadarEvent } from "@/data/types";

export const EMPTY_EVENT: RadarEvent = {
  id: "",
  badge: "DEVELOPING",
  timestamp: "",
  region: "—",
  theme: "Discovery",
  title: "Listening to the world tape",
  summary: "The engine clusters live evidence into events. None are selected yet.",
  story: "",
  probability: 0,
  probabilityDelta: 0,
  nodes: [],
  links: [],
  impacts: [],
  probabilityHistory: [],
  marketReaction: [],
  narrativeHeat: [],
  scenarios: [],
  gameTheory: {
    actor: "—",
    counterpart: "—",
    columns: [],
    rows: [],
    insight: "",
    players: [],
  },
  trades: [],
  evidence: [],
  takeaways: [],
  timeline: [],
  sentiment: [],
  sources: [],
  mode: "live",
  lifecycle: "candidate",
  importance: 0,
  entities: [],
  questions: [],
  invalidation: [],
  relatedEvents: [],
  horizons: [],
  expectedEvidence: [],
  knowledge: [],
  forecasts: [],
  claims: [],
  organizations: [],
  people: [],
  industries: [],
  commodities: [],
  economicVariables: [],
};
