/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as EventsRouteImport } from './routes/events'
import { Route as GameTheoryRouteImport } from './routes/game-theory'
import { Route as LearningRouteImport } from './routes/learning'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MacroRouteImport } from './routes/macro'
import { Route as MapsRouteImport } from './routes/maps'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ScenariosRouteImport } from './routes/scenarios'
import { Route as WatchlistsRouteImport } from './routes/watchlists'
import { Route as AssetsTickerRouteImport } from './routes/assets.$ticker'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const GameTheoryRoute = GameTheoryRouteImport.update({
  id: '/game-theory',
  path: '/game-theory',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningRoute = LearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MacroRoute = MacroRouteImport.update({
  id: '/macro',
  path: '/macro',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsRoute = MapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosRoute = ScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistsRoute = WatchlistsRouteImport.update({
  id: '/watchlists',
  path: '/watchlists',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsTickerRoute = AssetsTickerRouteImport.update({
  id: '/$ticker',
  path: '/$ticker',
  getParentRoute: () => AssetsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/assets': typeof AssetsRouteWithChildren
  '/docs': typeof DocsRoute
  '/events': typeof EventsRoute
  '/game-theory': typeof GameTheoryRoute
  '/learning': typeof LearningRoute
  '/login': typeof LoginRoute
  '/macro': typeof MacroRoute
  '/maps': typeof MapsRoute
  '/portfolio': typeof PortfolioRoute
  '/scenarios': typeof ScenariosRoute
  '/watchlists': typeof WatchlistsRoute
  '/assets/$ticker': typeof AssetsTickerRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/assets': typeof AssetsRouteWithChildren
  '/docs': typeof DocsRoute
  '/events': typeof EventsRoute
  '/game-theory': typeof GameTheoryRoute
  '/learning': typeof LearningRoute
  '/login': typeof LoginRoute
  '/macro': typeof MacroRoute
  '/maps': typeof MapsRoute
  '/portfolio': typeof PortfolioRoute
  '/scenarios': typeof ScenariosRoute
  '/watchlists': typeof WatchlistsRoute
  '/assets/$ticker': typeof AssetsTickerRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/assets': typeof AssetsRouteWithChildren
  '/docs': typeof DocsRoute
  '/events': typeof EventsRoute
  '/game-theory': typeof GameTheoryRoute
  '/learning': typeof LearningRoute
  '/login': typeof LoginRoute
  '/macro': typeof MacroRoute
  '/maps': typeof MapsRoute
  '/portfolio': typeof PortfolioRoute
  '/scenarios': typeof ScenariosRoute
  '/watchlists': typeof WatchlistsRoute
  '/assets/$ticker': typeof AssetsTickerRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/assets'
    | '/docs'
    | '/events'
    | '/game-theory'
    | '/learning'
    | '/login'
    | '/macro'
    | '/maps'
    | '/portfolio'
    | '/scenarios'
    | '/watchlists'
    | '/assets/$ticker'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/assets'
    | '/docs'
    | '/events'
    | '/game-theory'
    | '/learning'
    | '/login'
    | '/macro'
    | '/maps'
    | '/portfolio'
    | '/scenarios'
    | '/watchlists'
    | '/assets/$ticker'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/assets'
    | '/docs'
    | '/events'
    | '/game-theory'
    | '/learning'
    | '/login'
    | '/macro'
    | '/maps'
    | '/portfolio'
    | '/scenarios'
    | '/watchlists'
    | '/assets/$ticker'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AssetsRoute: typeof AssetsRouteWithChildren
  DocsRoute: typeof DocsRoute
  EventsRoute: typeof EventsRoute
  GameTheoryRoute: typeof GameTheoryRoute
  LearningRoute: typeof LearningRoute
  LoginRoute: typeof LoginRoute
  MacroRoute: typeof MacroRoute
  MapsRoute: typeof MapsRoute
  PortfolioRoute: typeof PortfolioRoute
  ScenariosRoute: typeof ScenariosRoute
  WatchlistsRoute: typeof WatchlistsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game-theory': {
      id: '/game-theory'
      path: '/game-theory'
      fullPath: '/game-theory'
      preLoaderRoute: typeof GameTheoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning': {
      id: '/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/macro': {
      id: '/macro'
      path: '/macro'
      fullPath: '/macro'
      preLoaderRoute: typeof MacroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps': {
      id: '/maps'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof MapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios': {
      id: '/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlists': {
      id: '/watchlists'
      path: '/watchlists'
      fullPath: '/watchlists'
      preLoaderRoute: typeof WatchlistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/$ticker': {
      id: '/assets/$ticker'
      path: '/$ticker'
      fullPath: '/assets/$ticker'
      preLoaderRoute: typeof AssetsTickerRouteImport
      parentRoute: typeof AssetsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AssetsRouteChildren {
  AssetsTickerRoute: typeof AssetsTickerRoute
}

const AssetsRouteChildren: AssetsRouteChildren = {
  AssetsTickerRoute: AssetsTickerRoute,
}

const AssetsRouteWithChildren =
  AssetsRoute._addFileChildren(AssetsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AssetsRoute: AssetsRouteWithChildren,
  DocsRoute: DocsRoute,
  EventsRoute: EventsRoute,
  GameTheoryRoute: GameTheoryRoute,
  LearningRoute: LearningRoute,
  LoginRoute: LoginRoute,
  MacroRoute: MacroRoute,
  MapsRoute: MapsRoute,
  PortfolioRoute: PortfolioRoute,
  ScenariosRoute: ScenariosRoute,
  WatchlistsRoute: WatchlistsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
